export const clientObjOne = {
  id: "clients",
  lightBg: true,
  //   lightText: false,
  //   lightTextDesc: true,
  //   topLine: "Lorem ipsum dolor",
  //   headline: "Lorem ipsum dolor sit amet",
  //   description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit,
  //       sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
  //       commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur`,
  //   buttonLabel: "Get Started",
  //   imgStart: false,
  //   img: require("../../images/svg-111.svg").default,
  //   alt: "Car",
  //   dark: true,
  //   primary: true,
  //   darkText: true,
  img1: require("../../images/logos/logo-1.png").default,
  img2: require("../../images/logos/logo-2.png").default,
  img3: require("../../images/logos/logo-3.png").default,
  img4: require("../../images/logos/logo-4.png").default,
  img5: require("../../images/logos/logo-5.png").default,
  img6: require("../../images/logos/logo-6.png").default,
  img7: require("../../images/logos/logo-7.png").default,
  img8: require("../../images/logos/logo-8.png").default,
  img9: require("../../images/logos/logo-9.png").default,
  img10: require("../../images/logos/logo-10.png").default,
};
