export const homeObjOne = {
  id: "about",
  lightBg: true,
  lightText: false,
  lightTextDesc: true,
  topLine: "Agence SITEM",
  headline: "Collaborez avec SITEM",
  description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
    sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, 
    commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur`,
  buttonLabel: "Get Started",
  imgStart: false,
  img: require("../../images/svg-111.svg").default,
  alt: "Car",
  dark: true,
  primary: true,
  darkText: true,
};
export const homeObjTow = {
  id: "discover",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Lorem ipsum",
  headline: "Lorem ipsum dolor sit amet, consectetur",
  description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
    sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, 
    commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur`,
  buttonLabel: "Learn More",
  imgStart: true,
  img: require("../../images/svg-11.svg").default,
  alt: "discover",
  dark: false,
  primary: true,
  darkText: true,
};
export const homeObjThree = {
  id: "team",
  lightBg: true,
  lightText: false,
  lightTextDesc: true,
  topLine: "SITEM COMPANY",
  headline: "Lorem ipsum dolor sit amet, consectetur",
  description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
    sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, 
    commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur`,
  buttonLabel: "Get Started",
  imgStart: false,
  img: require("../../images/svg-1.svg").default,
  alt: "idk",
  dark: true,
  primary: true,
  darkText: false,
};
